apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
spec:
  rules:
  - host: local.mongo-express.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend: 
          service:
            name: mongo-express-service-ingress
            port:
              number: 8888

